// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Studyo.Data;

#nullable disable

namespace Studyo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240207194746_migracao")]
    partial class migracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Studyo.Models.AnkiCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Completion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnkiCards");
                });

            modelBuilder.Entity("Studyo.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Antropologia Cultural",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Antropologia Social",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Antropologia Biológica",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Arqueologia",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Linguística Antropológica",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Funções e Gráficos",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sequências e Séries",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Probabilidades e Estatística",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Geometria no Plano e no Espaço",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Matemática Financeira",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Citologia",
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Genética",
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ecologia",
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Evolução",
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Anatomia Humana",
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Teoria Política",
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sistemas Políticos",
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "Política Comparada",
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Relações Internacionais",
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 20,
                            Name = "Literatura Grega",
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 21,
                            Name = "Literatura Latina",
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Literatura Renascentista",
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "Literatura Moderna",
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 24,
                            Name = "Fundamentos do Desenho",
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 25,
                            Name = "Perspectiva e Sombreamento",
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 26,
                            Name = "Desenho de Figura Humana",
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 27,
                            Name = "Desenho de Paisagem",
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "Direito Constitucional",
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 29,
                            Name = "Direito Civil",
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 30,
                            Name = "Direito Penal",
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 31,
                            Name = "Direito Administrativo",
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 32,
                            Name = "Direito Tributário",
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 33,
                            Name = "Microeconomia",
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 34,
                            Name = "Macroeconomia",
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 35,
                            Name = "Economia Internacional",
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 36,
                            Name = "Economia do Setor Público",
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 37,
                            Name = "Economia do Trabalho",
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 38,
                            Name = "Economia Monetária",
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 39,
                            Name = "Economia Industrial",
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 40,
                            Name = "Economia Ambiental",
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 41,
                            Name = "Economia do Desenvolvimento",
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 42,
                            Name = "Metafísica",
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 43,
                            Name = "Epistemologia",
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 44,
                            Name = "Ética",
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 45,
                            Name = "Estética",
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 46,
                            Name = "Filosofia da Mente",
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 47,
                            Name = "Filosofia da Ciência",
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 48,
                            Name = "Filosofia da Linguagem",
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 49,
                            Name = "Filosofia da Religião",
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 50,
                            Name = "Mecânica Clássica",
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 51,
                            Name = "Eletromagnetismo",
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 52,
                            Name = "Termodinâmica",
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 53,
                            Name = "Óptica",
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 54,
                            Name = "Física Quântica",
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 55,
                            Name = "Relatividade",
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 56,
                            Name = "Física Nuclear",
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 57,
                            Name = "Geografia Física",
                            SubjectId = 13
                        },
                        new
                        {
                            Id = 58,
                            Name = "Geografia Humana",
                            SubjectId = 13
                        },
                        new
                        {
                            Id = 59,
                            Name = "Geografia Econômica",
                            SubjectId = 13
                        },
                        new
                        {
                            Id = 60,
                            Name = "Geografia Política",
                            SubjectId = 13
                        },
                        new
                        {
                            Id = 61,
                            Name = "Geografia Urbana",
                            SubjectId = 14
                        },
                        new
                        {
                            Id = 62,
                            Name = "Geografia Rural",
                            SubjectId = 14
                        },
                        new
                        {
                            Id = 63,
                            Name = "Geografia do Brasil",
                            SubjectId = 14
                        },
                        new
                        {
                            Id = 64,
                            Name = "Geografia da Europa",
                            SubjectId = 14
                        },
                        new
                        {
                            Id = 65,
                            Name = "Fundamentos da Geometria Descritiva",
                            SubjectId = 15
                        },
                        new
                        {
                            Id = 66,
                            Name = "Projeções Ortogonais",
                            SubjectId = 15
                        },
                        new
                        {
                            Id = 67,
                            Name = "Projeções Oblíquas",
                            SubjectId = 15
                        },
                        new
                        {
                            Id = 68,
                            Name = "Interseções e Desenvolvimentos",
                            SubjectId = 15
                        },
                        new
                        {
                            Id = 69,
                            Name = "Gramática Grega",
                            SubjectId = 16
                        },
                        new
                        {
                            Id = 70,
                            Name = "Literatura Grega Clássica",
                            SubjectId = 16
                        },
                        new
                        {
                            Id = 71,
                            Name = "Mitologia Grega",
                            SubjectId = 16
                        },
                        new
                        {
                            Id = 72,
                            Name = "História da Grécia Antiga",
                            SubjectId = 16
                        },
                        new
                        {
                            Id = 73,
                            Name = "Pré-História",
                            SubjectId = 17
                        },
                        new
                        {
                            Id = 74,
                            Name = "Antiguidade",
                            SubjectId = 17
                        },
                        new
                        {
                            Id = 75,
                            Name = "Idade Média",
                            SubjectId = 17
                        },
                        new
                        {
                            Id = 76,
                            Name = "Idade Moderna",
                            SubjectId = 17
                        },
                        new
                        {
                            Id = 77,
                            Name = "Idade Contemporânea",
                            SubjectId = 17
                        },
                        new
                        {
                            Id = 78,
                            Name = "História do Brasil",
                            SubjectId = 18
                        },
                        new
                        {
                            Id = 79,
                            Name = "História de Portugal",
                            SubjectId = 18
                        },
                        new
                        {
                            Id = 80,
                            Name = "História da América",
                            SubjectId = 18
                        },
                        new
                        {
                            Id = 81,
                            Name = "História da África",
                            SubjectId = 18
                        },
                        new
                        {
                            Id = 82,
                            Name = "História da Ásia",
                            SubjectId = 18
                        },
                        new
                        {
                            Id = 83,
                            Name = "Arte na Pré-História",
                            SubjectId = 19
                        },
                        new
                        {
                            Id = 84,
                            Name = "Arte na Antiguidade",
                            SubjectId = 19
                        },
                        new
                        {
                            Id = 85,
                            Name = "Arte na Idade Média",
                            SubjectId = 19
                        },
                        new
                        {
                            Id = 86,
                            Name = "Arte no Renascimento",
                            SubjectId = 19
                        },
                        new
                        {
                            Id = 87,
                            Name = "Arte Contemporânea",
                            SubjectId = 19
                        },
                        new
                        {
                            Id = 88,
                            Name = "Gramática Básica",
                            SubjectId = 20
                        },
                        new
                        {
                            Id = 89,
                            Name = "Vocabulário Básico",
                            SubjectId = 20
                        },
                        new
                        {
                            Id = 90,
                            Name = "Conversação Básica",
                            SubjectId = 20
                        },
                        new
                        {
                            Id = 91,
                            Name = "Leitura e Compreensão de Textos",
                            SubjectId = 20
                        },
                        new
                        {
                            Id = 92,
                            Name = "Gramática Avançada",
                            SubjectId = 21
                        },
                        new
                        {
                            Id = 93,
                            Name = "Vocabulário Avançado",
                            SubjectId = 21
                        },
                        new
                        {
                            Id = 94,
                            Name = "Conversação Avançada",
                            SubjectId = 21
                        },
                        new
                        {
                            Id = 95,
                            Name = "Leitura e Compreensão de Textos Avançados",
                            SubjectId = 21
                        },
                        new
                        {
                            Id = 96,
                            Name = "Gramática Proficiente",
                            SubjectId = 22
                        },
                        new
                        {
                            Id = 97,
                            Name = "Vocabulário Proficiente",
                            SubjectId = 22
                        },
                        new
                        {
                            Id = 98,
                            Name = "Conversação Proficiente",
                            SubjectId = 22
                        },
                        new
                        {
                            Id = 99,
                            Name = "Leitura e Compreensão de Textos Proficientes",
                            SubjectId = 22
                        },
                        new
                        {
                            Id = 100,
                            Name = "Gramática Latina Básica",
                            SubjectId = 23
                        },
                        new
                        {
                            Id = 101,
                            Name = "Vocabulário Latino Básico",
                            SubjectId = 23
                        },
                        new
                        {
                            Id = 102,
                            Name = "Leitura e Compreensão de Textos Latinos Básicos",
                            SubjectId = 23
                        },
                        new
                        {
                            Id = 103,
                            Name = "Gramática Latina Avançada",
                            SubjectId = 24
                        },
                        new
                        {
                            Id = 104,
                            Name = "Vocabulário Latino Avançado",
                            SubjectId = 24
                        },
                        new
                        {
                            Id = 105,
                            Name = "Leitura e Compreensão de Textos Latinos Avançados",
                            SubjectId = 24
                        },
                        new
                        {
                            Id = 106,
                            Name = "Literatura Medieval Portuguesa",
                            SubjectId = 25
                        },
                        new
                        {
                            Id = 107,
                            Name = "Renascimento e Classicismo",
                            SubjectId = 25
                        },
                        new
                        {
                            Id = 108,
                            Name = "Barroco e Neoclassicismo",
                            SubjectId = 25
                        },
                        new
                        {
                            Id = 109,
                            Name = "Romantismo",
                            SubjectId = 25
                        },
                        new
                        {
                            Id = 110,
                            Name = "Realismo e Naturalismo",
                            SubjectId = 25
                        },
                        new
                        {
                            Id = 111,
                            Name = "Modernismo e Contemporâneo",
                            SubjectId = 25
                        },
                        new
                        {
                            Id = 112,
                            Name = "Literatura Angolana",
                            SubjectId = 26
                        },
                        new
                        {
                            Id = 113,
                            Name = "Literatura Brasileira",
                            SubjectId = 26
                        },
                        new
                        {
                            Id = 114,
                            Name = "Literatura Moçambicana",
                            SubjectId = 26
                        },
                        new
                        {
                            Id = 115,
                            Name = "Literatura Cabo-Verdiana",
                            SubjectId = 26
                        },
                        new
                        {
                            Id = 116,
                            Name = "Materiais Metálicos",
                            SubjectId = 27
                        },
                        new
                        {
                            Id = 117,
                            Name = "Materiais Cerâmicos",
                            SubjectId = 27
                        },
                        new
                        {
                            Id = 118,
                            Name = "Materiais Poliméricos",
                            SubjectId = 27
                        },
                        new
                        {
                            Id = 119,
                            Name = "Materiais Compósitos",
                            SubjectId = 27
                        },
                        new
                        {
                            Id = 120,
                            Name = "Álgebra",
                            SubjectId = 28
                        },
                        new
                        {
                            Id = 121,
                            Name = "Geometria",
                            SubjectId = 28
                        },
                        new
                        {
                            Id = 122,
                            Name = "Cálculo",
                            SubjectId = 28
                        },
                        new
                        {
                            Id = 123,
                            Name = "Funções Reais de Variável Real",
                            SubjectId = 29
                        },
                        new
                        {
                            Id = 124,
                            Name = "Sequências e Sucessões",
                            SubjectId = 29
                        },
                        new
                        {
                            Id = 125,
                            Name = "Limites e Continuidade",
                            SubjectId = 29
                        },
                        new
                        {
                            Id = 126,
                            Name = "Diferenciação",
                            SubjectId = 29
                        },
                        new
                        {
                            Id = 127,
                            Name = "Arte na Pré-História",
                            SubjectId = 30
                        },
                        new
                        {
                            Id = 128,
                            Name = "Arte na Antiguidade",
                            SubjectId = 30
                        },
                        new
                        {
                            Id = 129,
                            Name = "Arte na Idade Média",
                            SubjectId = 30
                        },
                        new
                        {
                            Id = 130,
                            Name = "Arte no Renascimento",
                            SubjectId = 30
                        },
                        new
                        {
                            Id = 131,
                            Name = "Arte Contemporânea",
                            SubjectId = 30
                        },
                        new
                        {
                            Id = 132,
                            Name = "Pintura",
                            SubjectId = 31
                        },
                        new
                        {
                            Id = 133,
                            Name = "Escultura",
                            SubjectId = 31
                        },
                        new
                        {
                            Id = 134,
                            Name = "Cerâmica",
                            SubjectId = 31
                        },
                        new
                        {
                            Id = 135,
                            Name = "Fotografia",
                            SubjectId = 31
                        },
                        new
                        {
                            Id = 136,
                            Name = "Design Gráfico",
                            SubjectId = 32
                        },
                        new
                        {
                            Id = 137,
                            Name = "Animação Digital",
                            SubjectId = 32
                        },
                        new
                        {
                            Id = 138,
                            Name = "Produção de Vídeo",
                            SubjectId = 32
                        },
                        new
                        {
                            Id = 139,
                            Name = "Programação Web",
                            SubjectId = 32
                        },
                        new
                        {
                            Id = 140,
                            Name = "Gramática",
                            SubjectId = 33
                        },
                        new
                        {
                            Id = 141,
                            Name = "Literatura Portuguesa",
                            SubjectId = 33
                        },
                        new
                        {
                            Id = 142,
                            Name = "Oratória",
                            SubjectId = 33
                        },
                        new
                        {
                            Id = 143,
                            Name = "Escrita Criativa",
                            SubjectId = 33
                        },
                        new
                        {
                            Id = 144,
                            Name = "Psicologia Cognitiva",
                            SubjectId = 34
                        },
                        new
                        {
                            Id = 145,
                            Name = "Psicologia Social",
                            SubjectId = 34
                        },
                        new
                        {
                            Id = 146,
                            Name = "Psicologia do Desenvolvimento",
                            SubjectId = 34
                        },
                        new
                        {
                            Id = 147,
                            Name = "Psicologia Clínica",
                            SubjectId = 34
                        },
                        new
                        {
                            Id = 148,
                            Name = "Química Geral",
                            SubjectId = 35
                        },
                        new
                        {
                            Id = 149,
                            Name = "Química Orgânica",
                            SubjectId = 35
                        },
                        new
                        {
                            Id = 150,
                            Name = "Química Inorgânica",
                            SubjectId = 35
                        },
                        new
                        {
                            Id = 151,
                            Name = "Química Analítica",
                            SubjectId = 35
                        },
                        new
                        {
                            Id = 152,
                            Name = "Sociologia Geral",
                            SubjectId = 36
                        },
                        new
                        {
                            Id = 153,
                            Name = "Sociologia da Educação",
                            SubjectId = 36
                        },
                        new
                        {
                            Id = 154,
                            Name = "Sociologia do Trabalho",
                            SubjectId = 36
                        },
                        new
                        {
                            Id = 155,
                            Name = "Sociologia Urbana",
                            SubjectId = 36
                        });
                });

            modelBuilder.Entity("Studyo.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Studyo.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Studyo.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Studyo.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Antropologia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aplicações Matemáticas B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biologia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ciência Política"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Clássicos da Literatura"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Desenho A"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Direito"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Economia A"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Economia C"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Filosofia A"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Filosofia B"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Física"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Geografia A"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Geografia C"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Geometria Descritiva A"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Grego"
                        },
                        new
                        {
                            Id = 17,
                            Name = "História A"
                        },
                        new
                        {
                            Id = 18,
                            Name = "História B"
                        },
                        new
                        {
                            Id = 19,
                            Name = "História da Cultura e das Artes"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Língua Estrangeira I"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Língua Estrangeira II"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Língua Estrangeira III"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Latim A"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Latim B"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Literatura Portuguesa"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Literatura de Língua Portuguesa"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Materiais e Tecnologias"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Matemática A"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Matemática B"
                        },
                        new
                        {
                            Id = 30,
                            Name = "História da Cultura e das Artes"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Oficina de Artes"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Oficina de Multimédia B"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Português"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Psicologia B"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Química"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Sociologia"
                        });
                });

            modelBuilder.Entity("Studyo.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkshopContent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("WorkshopContent")
                        .IsUnique();

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("Studyo.Models.WorkshopContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("WorkshopContents");
                });

            modelBuilder.Entity("Studyo.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Studyo.Models.Chapter", b =>
                {
                    b.HasOne("Studyo.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Studyo.Models.Material", b =>
                {
                    b.HasOne("Studyo.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Studyo.Models.Workshop", b =>
                {
                    b.HasOne("Studyo.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Studyo.Models.WorkshopContent", "Content")
                        .WithOne("workshop")
                        .HasForeignKey("Studyo.Models.Workshop", "WorkshopContent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Studyo.Models.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("Studyo.Models.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Studyo.Models.Subject", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Studyo.Models.WorkshopContent", b =>
                {
                    b.Navigation("workshop")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
